language: java
script: mvn clean install -Dmaven.test.skip=true
before_deploy: "echo 'ready?'"
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "JTdiA8MBmcU76In7tv1aGUn8OpgnrXjw/OR8wTZMDJcq1DEvMe3bK06g6P4k76+9XQyOkoHBhLDg6UbrgjDYoQ3wbZ8HMQBWzJafWyWjNtysXcGmGpMgAWZt6798LRmzlghKxhfcuGxkU3d9fLe4ayDUk+81xO8msMTzrrSqHacI4eCFv9P1/0/KZXXnWQZ+uNXA/6Fdx0VXEzlyLL1HeQXoZf/zDySsHLcZIZ+IBZtQyR8oLnOOMkxUqjY0oeedul1JSIi8Mpifvk4wKnlXDTQTgYVyY3aSqXl7AglXvH/QZSeUtUIKObphGQ8d/j2WSLX2QHKRIJhNPAfOKGffcnJlOMuHHuVv1TsxAb50yPuBiseyK8YtbtSzfTKQsviaKsuYic9TN6F4ovrI4s55kZt08GkOG7eb3QZeeLZyMLoEs7mJRr6G7Q8C49QjU0dCny/dVxt2BE5TFscrHvvjOHBn6kkBmW4D4zHBVymGzsIIJXBbLqds70pux/axWf4qSNlZD+Wcbae6t0ovh5/V/I3ugHozesV0NBNbxOH8lyyi+RSPWnKQ2uf3h7lndSNMPck3nzU8wWZ5AZwUY2h1YrxcJXjnIDmsRH0h13QHGnaymsmkzt5cuWFZziIUu/wvbwnuBdo8LT1L+ehAPFp9iP1ABHfaFAzJUqb1bFvEzaE="
  secret_access_key:
    secure: "fCWX74lrTVYJrGaQzNnfmqt9hyn8EUJWkqeyl4tVjX9Zm6alplajf4F5iFIYZ0KqN8qIBQWiMMXWd6Nfp0GC5qXLRMHs12LB1zvO0hSj1wM/YY5iBufB8hE/6YMGZCWvpE4KYjlZUxlY4NxJS56pvt0/NdFJMpgjGg03PN2rRDIm3Vx4KXVjcBDXKtOUXFsGgnL4eZvmahLEzyvBC8dvk/CDm4jlUu54k0CYC7f1lUjjcsgtPIgnuR7LvfMU2UjjHMyHQqYev4VCiaLKpVRqrIKznfVmfenJjiSVnl3OTCgbNsPEnzpmmNl7f06XNTwhzLhPTw3CUvPb4iscjIdTNkuFUxzbauZIIggCaxgF2liF50BuQ/grSRhz/UfIoiNtw92jRuaHuurzwRZqs/fk2Srqy1QTiCxFiXoNjvU6TH07eIqVxSGqejvq/w93rMbCI623Y67ViM4/WZ3BYRNA4ivMkKJLjH5F/HnSoObSo1grYURfRJGP6PJKdxgdlSoxecbbsnlOQ268G+L43IRrYgkNBzM9yDLNH1oG4Z6qPKJbFcC/CZuV6wQccHnVqf7ppDTvN8k5LeEaeQqc+XxreXxc5q77Cz75DPvs/VtpL2+8+6BpE3n8yJzcTBfARqDbitWFAtxafXG/a3Jbqt1fV5yYp+0ECxN9qpFMEu+YaW8="
  region: "eu-west-2"
  app: "crypto"
  env: "crypto-dev"
  bucket_name: "elasticbeanstalk-eu-west-2-185149189967"

after_deploy: "echo 'deployed'"